# Generated by Django 3.1.6 on 2021-02-11 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('artistName', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('bookedTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.tickets')),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.user')),
            ],
        ),
    ]
