# Generated by Django 3.1.6 on 2021-02-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20210212_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='artistName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
